### ISSUE TITLE
beta checklist

### ISSUE THREAD

**Issue by papertek** [TheaceaeCollective/porter-wiki-frontend#2]
## main
- [ ] RSS feed (not required) - juli
- [ ] editor (this is going to suck) - emma
- [ ] profile view (no polls required) - john and matt
- [ ] settings page - john and matt
- [ ] language switching - uhh idk

## needs fixing
- [x] fucky code with blog and news view - juli (I FIXED DAT SHIT :>)

**Comment by YellowHNY** [comment]
<ins>**Add To Backburner List**</ins>

- [ ] Moderation Page for mods (will explain in detail at a later point)
